In [1]:
import numpy as np
import os

from pathlib import Path

# change working directory to make src visible
os.chdir(Path.cwd().parent)

from src.dataset import SPDEventsDataset
from src.normalization import ConstraintsNormalizer, TrackParamsNormalizer

In [2]:
np.random.seed(42)

dataset = SPDEventsDataset(
    hits_normalizer=ConstraintsNormalizer(),
    track_params_normalizer=TrackParamsNormalizer(),
    shuffle=True
)

In [3]:
sample = dataset[0]

In [4]:
sample

{'hits': array([[ 0.59280544,  0.23586112,  0.81287491],
        [-0.27955427,  0.459404  , -0.98133676],
        [-0.2749876 , -0.64170251, -0.96161545],
        ...,
        [-0.7404729 ,  0.50909341,  0.17553872],
        [ 0.70824555, -0.11907849,  0.21250588],
        [ 0.25619556,  0.2771329 , -0.2644813 ]]),
 'hit_labels': array([-1, -1, -1, -1, -1,  4, -1,  2,  2,  3, -1, -1, -1, -1,  3, -1, -1,
         0, -1, -1, -1, -1,  1,  2, -1,  0, -1,  4, -1, -1, -1,  3,  1,  0,
        -1, -1, -1,  4,  2, -1,  3, -1, -1, -1, -1, -1, -1, -1, -1, -1,  2,
        -1, -1,  0, -1,  0, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  3, -1,  3,  2,
        -1, -1,  3, -1, -1,  0, -1, -1, -1, -1,  0, -1,  1, -1,  2,  1, -1,
        -1,  3,  4,  1, -1, -1, -1,  0, -1, -1,  4, -1, -1, -1, -1,  0, -1,
        -1,  1,  0, -1, -1,  2, -1, -1,  3, -1, -1,  0, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1,  3, -1, -1,  0,  2, -1, -1, -1, -

In [5]:
sample["hits"].shape

(665, 3)

In [6]:
sample["hit_labels"].shape

(665,)

In [7]:
sample["param_labels"]

array([ 0,  1,  3,  2,  4, -1, -1, -1, -1, -1], dtype=int32)

In [8]:
np.round(sample["params"], 3)

array([[0.503, 0.499, 0.529, 0.156, 0.156, 0.845, 0.   , 1.   ],
       [0.503, 0.499, 0.529, 0.648, 0.001, 0.595, 1.   , 0.   ],
       [0.503, 0.499, 0.529, 0.215, 0.377, 0.874, 0.   , 1.   ],
       [0.503, 0.499, 0.529, 0.954, 0.915, 0.584, 1.   , 0.   ],
       [0.503, 0.499, 0.529, 0.974, 0.986, 0.37 , 1.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ]],
      dtype=float32)

In [9]:
vectorized_denorm = np.vectorize(dataset.track_params_normalizer.denormalize)
orig_params = np.apply_along_axis(
    dataset.track_params_normalizer.denormalize, 
    axis=1, 
    arr=sample["params"][:5]
)
np.round(orig_params, 2)

array([[  4.97,  -1.38, 139.2 , 240.42,   0.98,   2.65,   1.  ],
       [  4.97,  -1.38, 139.2 , 682.92,   0.  ,   1.87,  -1.  ],
       [  4.97,  -1.38, 139.2 , 293.13,   2.37,   2.74,   1.  ],
       [  4.97,  -1.38, 139.2 , 958.54,   5.75,   1.83,  -1.  ],
       [  4.97,  -1.38, 139.2 , 976.96,   6.2 ,   1.16,  -1.  ]],
      dtype=float32)

In [10]:
dataset.track_params_normalizer = None
sample = dataset[0]
np.round(sample["params"], 2)

array([[  4.97,  -1.38, 139.2 , 240.42,   0.98,   2.65,   1.  ],
       [  4.97,  -1.38, 139.2 , 682.92,   0.  ,   1.87,  -1.  ],
       [  4.97,  -1.38, 139.2 , 293.13,   2.37,   2.74,   1.  ],
       [  4.97,  -1.38, 139.2 , 958.54,   5.75,   1.83,  -1.  ],
       [  4.97,  -1.38, 139.2 , 976.96,   6.2 ,   1.16,  -1.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ]],
      dtype=float32)